def convert_mark(mark, exponent)
    (mark**exponent * (100.0/100**exponent)).round
end

puts "<!DOCTYPE html>"
puts "<html lang='en-US'>"
puts "<head>"
puts "  <meta charset='utf-8'>"
puts "  <title>Convert Marks!</title>"
puts "  <style>"
puts "    * {"
puts "         font-family: 'Times New Roman', Times, serif;"
puts "    }"
puts "    h1 {"
puts "         margin-left: 10px;"
puts "         text-align: center"
puts "    }"
puts "    p {"
puts "         font-size: 2.0em;"
puts "         margin-left: 10px;"
puts "    }"
puts "    table {"
puts "         width: 30%;"
puts "         margin: 30px 20px 30px 500px;"
puts "         border-collapse: collapse;"
puts "    }"
puts "    th, td {"
puts "         border: 2px solid blue;"
puts "         padding: 10px 20px 10px 20px;"
puts "         text-align: center;"
puts "    }"
puts "    tr:nth-child(even) {"
puts "         background-color: gray;"
puts "    }"
puts "  </style>"
puts "</head>"
puts "<body>"
puts "  <h1>Convert marks!</h1>"
puts "  <p>Thre are 100 elements"
puts "  <table>"
puts "    <tr>"
puts "      <th>Before</th>"
puts "      <th>After</th>"
puts "    </tr>"
(0..100).each do |n|
puts "    <tr>"
puts "      <td>#{n}</td>"
puts "      <td>#{convert_mark(n, 0.5)}</td>"
puts "    </tr>"
end
puts "  </table>"
puts "  <p>This table shows points changes before and after .</p>"
puts "</body>"
puts "</html>"